elasticsearch:
  build: elasticsearch/
  volumes:
    - ./elasticsearch/config:/usr/share/elasticsearch/config
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  build: kibana/
  volumes:
    - ./kibana/config:/opt/kibana/config
  ports:
    - "5601:5601"
  links:
    - elasticsearch
